// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/testRcppNew_types.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Random::Rminstd_rand<Rcpp::NumericVector>
template Rcpp::NumericVector Random::Rminstd_rand<Rcpp::NumericVector>(std::size_t length);
RcppExport SEXP _testRcppNew_minstd_rand(SEXP lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::size_t >::type length(lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(Random::Rminstd_rand<Rcpp::NumericVector>(length));
    return rcpp_result_gen;
END_RCPP
}
// Random::Rmt19937<Rcpp::NumericVector>
template Rcpp::NumericVector Random::Rmt19937<Rcpp::NumericVector>(std::size_t length);
RcppExport SEXP _testRcppNew_mt19937(SEXP lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::size_t >::type length(lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(Random::Rmt19937<Rcpp::NumericVector>(length));
    return rcpp_result_gen;
END_RCPP
}
// Random::Rknuth_b<Rcpp::NumericVector>
template Rcpp::NumericVector Random::Rknuth_b<Rcpp::NumericVector>(std::size_t length);
RcppExport SEXP _testRcppNew_knuth_b(SEXP lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::size_t >::type length(lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(Random::Rknuth_b<Rcpp::NumericVector>(length));
    return rcpp_result_gen;
END_RCPP
}
// Random::Rminstd_rand<Rcpp::IntegerVector>
template Rcpp::IntegerVector Random::Rminstd_rand<Rcpp::IntegerVector>(std::size_t length);
RcppExport SEXP _testRcppNew_minstd_rand_int(SEXP lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::size_t >::type length(lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(Random::Rminstd_rand<Rcpp::IntegerVector>(length));
    return rcpp_result_gen;
END_RCPP
}
// Random::Rmt19937<Rcpp::IntegerVector>
template Rcpp::IntegerVector Random::Rmt19937<Rcpp::IntegerVector>(std::size_t length);
RcppExport SEXP _testRcppNew_mt19937_int(SEXP lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::size_t >::type length(lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(Random::Rmt19937<Rcpp::IntegerVector>(length));
    return rcpp_result_gen;
END_RCPP
}
// Random::Rknuth_b<Rcpp::IntegerVector>
template Rcpp::IntegerVector Random::Rknuth_b<Rcpp::IntegerVector>(std::size_t length);
RcppExport SEXP _testRcppNew_knuth_b_int(SEXP lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::size_t >::type length(lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(Random::Rknuth_b<Rcpp::IntegerVector>(length));
    return rcpp_result_gen;
END_RCPP
}
// Random::sample<Rcpp::NumericVector>
template Rcpp::NumericVector Random::sample<Rcpp::NumericVector>(Rcpp::NumericVector x, std::size_t size, bool replace);
RcppExport SEXP _testRcppNew_sample(SEXP xSEXP, SEXP sizeSEXP, SEXP replaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type replace(replaceSEXP);
    rcpp_result_gen = Rcpp::wrap(Random::sample<Rcpp::NumericVector>(x, size, replace));
    return rcpp_result_gen;
END_RCPP
}
// Random::sample<Rcpp::IntegerVector>
template Rcpp::IntegerVector Random::sample<Rcpp::IntegerVector>(Rcpp::IntegerVector x, std::size_t size, bool replace);
RcppExport SEXP _testRcppNew_sample_int(SEXP xSEXP, SEXP sizeSEXP, SEXP replaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type replace(replaceSEXP);
    rcpp_result_gen = Rcpp::wrap(Random::sample<Rcpp::IntegerVector>(x, size, replace));
    return rcpp_result_gen;
END_RCPP
}
// Str::startsWith
bool Str::startsWith(std::string str, std::string substr);
RcppExport SEXP _testRcppNew_startsWith(SEXP strSEXP, SEXP substrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type str(strSEXP);
    Rcpp::traits::input_parameter< std::string >::type substr(substrSEXP);
    rcpp_result_gen = Rcpp::wrap(Str::startsWith(str, substr));
    return rcpp_result_gen;
END_RCPP
}
// Str::endsWith
bool Str::endsWith(std::string str, std::string substr);
RcppExport SEXP _testRcppNew_endsWith(SEXP strSEXP, SEXP substrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type str(strSEXP);
    Rcpp::traits::input_parameter< std::string >::type substr(substrSEXP);
    rcpp_result_gen = Rcpp::wrap(Str::endsWith(str, substr));
    return rcpp_result_gen;
END_RCPP
}
// Str::replaceSubstring
std::string Str::replaceSubstring(std::string s, std::string oldSubstr, std::string newSubstr);
RcppExport SEXP _testRcppNew_replaceSubstring(SEXP sSEXP, SEXP oldSubstrSEXP, SEXP newSubstrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    Rcpp::traits::input_parameter< std::string >::type oldSubstr(oldSubstrSEXP);
    Rcpp::traits::input_parameter< std::string >::type newSubstr(newSubstrSEXP);
    rcpp_result_gen = Rcpp::wrap(Str::replaceSubstring(s, oldSubstr, newSubstr));
    return rcpp_result_gen;
END_RCPP
}
// Str::toTable
std::map<std::string, double> Str::toTable(std::string x);
RcppExport SEXP _testRcppNew_toTable_char(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Str::toTable(x));
    return rcpp_result_gen;
END_RCPP
}
// add
int add(int a, int b);
RcppExport SEXP _testRcppNew_add(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(add(a, b));
    return rcpp_result_gen;
END_RCPP
}
// multiply
double multiply(double x, double y);
RcppExport SEXP _testRcppNew_multiply(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(multiply(x, y));
    return rcpp_result_gen;
END_RCPP
}
// identity<Rcpp::NumericVector>
template Rcpp::NumericVector identity<Rcpp::NumericVector>(Rcpp::NumericVector x);
RcppExport SEXP _testRcppNew_identity_numeric(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(identity<Rcpp::NumericVector>(x));
    return rcpp_result_gen;
END_RCPP
}
// identity< Rcpp::IntegerVector   >
template Rcpp::IntegerVector identity< Rcpp::IntegerVector   >(Rcpp::IntegerVector x);
RcppExport SEXP _testRcppNew_identity_integer(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(identity< Rcpp::IntegerVector   >(x));
    return rcpp_result_gen;
END_RCPP
}
// identity< Rcpp::CharacterVector >
template Rcpp::CharacterVector identity< Rcpp::CharacterVector >(Rcpp::CharacterVector x);
RcppExport SEXP _testRcppNew_identity_character(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(identity< Rcpp::CharacterVector >(x));
    return rcpp_result_gen;
END_RCPP
}
// combine<              Rcpp   ::      NumericVector,       Rcpp::IntegerVector      >
template Rcpp::List combine<              Rcpp   ::      NumericVector,       Rcpp::IntegerVector      >(const Rcpp::NumericVector& y, const Rcpp::IntegerVector& x);
RcppExport SEXP _testRcppNew_combine_a(SEXP ySEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(combine<              Rcpp   ::      NumericVector,       Rcpp::IntegerVector      >(y, x));
    return rcpp_result_gen;
END_RCPP
}
// combine<Rcpp  ::  IntegerVector     ,   Rcpp::  NumericVector  >
template Rcpp ::    List combine<Rcpp  ::  IntegerVector     ,   Rcpp::  NumericVector  >(const Rcpp::IntegerVector& y, const Rcpp::NumericVector& x);
RcppExport SEXP _testRcppNew_combine_b(SEXP ySEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(combine<Rcpp  ::  IntegerVector     ,   Rcpp::  NumericVector  >(y, x));
    return rcpp_result_gen;
END_RCPP
}
// computeSum<Rcpp :: NumericVector>
template double computeSum<Rcpp :: NumericVector>(const Rcpp::NumericVector& x);
RcppExport SEXP _testRcppNew_computeSum_a(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(computeSum<Rcpp :: NumericVector>(x));
    return rcpp_result_gen;
END_RCPP
}
// computeSum<Rcpp:: IntegerVector>
template double computeSum<Rcpp:: IntegerVector>(const Rcpp::     IntegerVector& x);
RcppExport SEXP _testRcppNew_computeSum_b(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::     IntegerVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(computeSum<Rcpp:: IntegerVector>(x));
    return rcpp_result_gen;
END_RCPP
}
// math::square< double >
template double math::square< double >(double x);
RcppExport SEXP _testRcppNew_math_square_a(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(math::square< double >(x));
    return rcpp_result_gen;
END_RCPP
}
// math::square<int>
template int math::square<int>(int x);
RcppExport SEXP _testRcppNew_math_square_b(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(math::square<int>(x));
    return rcpp_result_gen;
END_RCPP
}
// app::core::version1
std::string app::core::version1();
RcppExport SEXP _testRcppNew_app_core_version1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(app::core::version1());
    return rcpp_result_gen;
END_RCPP
}
// identity<std::string>
template <> std::string identity<std::string>(std::string value);
RcppExport SEXP _testRcppNew_identity_string(SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(identity<std::string>(value));
    return rcpp_result_gen;
END_RCPP
}
// test::addValues<double , double>
template void test::addValues<double , double>(const double& y, const double& x);
RcppExport SEXP _testRcppNew_test_addValues_a(SEXP ySEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double& >::type x(xSEXP);
    test::addValues<double , double>(y, x);
    return R_NilValue;
END_RCPP
}
// test::addValues<Rcpp ::NumericVector,  Rcpp::NumericVector>
template void test::addValues<Rcpp ::NumericVector,  Rcpp::NumericVector>(const Rcpp::NumericVector& y, const Rcpp::NumericVector& x);
RcppExport SEXP _testRcppNew_test_addValues_b(SEXP ySEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    test::addValues<Rcpp ::NumericVector,  Rcpp::NumericVector>(y, x);
    return R_NilValue;
END_RCPP
}
// piii
double piii();
RcppExport SEXP _testRcppNew_pi_func() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(piii());
    return rcpp_result_gen;
END_RCPP
}
// util::hashCode
inline int util::hashCode(const std::string& key);
RcppExport SEXP _testRcppNew_util_hashCode(SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type key(keySEXP);
    rcpp_result_gen = Rcpp::wrap(util::hashCode(key));
    return rcpp_result_gen;
END_RCPP
}
// mean<Rcpp::NumericVector>
template Rcpp::NumericVector mean<Rcpp::NumericVector>(const Rcpp::NumericVector& x);
RcppExport SEXP _testRcppNew_mean1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mean<Rcpp::NumericVector>(x));
    return rcpp_result_gen;
END_RCPP
}
// mean<Rcpp:: IntegerVector>
template Rcpp:: IntegerVector mean<Rcpp:: IntegerVector>(const Rcpp::IntegerVector& x);
RcppExport SEXP _testRcppNew_mean(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mean<Rcpp:: IntegerVector>(x));
    return rcpp_result_gen;
END_RCPP
}
// gcd<int>
template int gcd<int>(int x, int y);
RcppExport SEXP _testRcppNew_gcd_a(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(gcd<int>(x, y));
    return rcpp_result_gen;
END_RCPP
}
// gcd<long>
template long gcd<long>(long x, long y);
RcppExport SEXP _testRcppNew_gcd_b(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long >::type x(xSEXP);
    Rcpp::traits::input_parameter< long >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(gcd<long>(x, y));
    return rcpp_result_gen;
END_RCPP
}
// process<Rcpp::List>
template void process<Rcpp::List>(const Rcpp::List& x);
RcppExport SEXP _testRcppNew_process(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type x(xSEXP);
    process<Rcpp::List>(x);
    return R_NilValue;
END_RCPP
}
// equal
inline bool equal(int a, int b);
RcppExport SEXP _testRcppNew_equal_func(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(equal(a, b));
    return rcpp_result_gen;
END_RCPP
}
// average<double>
template double average<double>(double x, double y);
RcppExport SEXP _testRcppNew_average_a(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(average<double>(x, y));
    return rcpp_result_gen;
END_RCPP
}
// average<int>
template int average<int>(int x, int y);
RcppExport SEXP _testRcppNew_average_b(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(average<int>(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_testRcppNew_minstd_rand", (DL_FUNC) &_testRcppNew_minstd_rand, 1},
    {"_testRcppNew_mt19937", (DL_FUNC) &_testRcppNew_mt19937, 1},
    {"_testRcppNew_knuth_b", (DL_FUNC) &_testRcppNew_knuth_b, 1},
    {"_testRcppNew_minstd_rand_int", (DL_FUNC) &_testRcppNew_minstd_rand_int, 1},
    {"_testRcppNew_mt19937_int", (DL_FUNC) &_testRcppNew_mt19937_int, 1},
    {"_testRcppNew_knuth_b_int", (DL_FUNC) &_testRcppNew_knuth_b_int, 1},
    {"_testRcppNew_sample", (DL_FUNC) &_testRcppNew_sample, 3},
    {"_testRcppNew_sample_int", (DL_FUNC) &_testRcppNew_sample_int, 3},
    {"_testRcppNew_startsWith", (DL_FUNC) &_testRcppNew_startsWith, 2},
    {"_testRcppNew_endsWith", (DL_FUNC) &_testRcppNew_endsWith, 2},
    {"_testRcppNew_replaceSubstring", (DL_FUNC) &_testRcppNew_replaceSubstring, 3},
    {"_testRcppNew_toTable_char", (DL_FUNC) &_testRcppNew_toTable_char, 1},
    {"_testRcppNew_add", (DL_FUNC) &_testRcppNew_add, 2},
    {"_testRcppNew_multiply", (DL_FUNC) &_testRcppNew_multiply, 2},
    {"_testRcppNew_identity_numeric", (DL_FUNC) &_testRcppNew_identity_numeric, 1},
    {"_testRcppNew_identity_integer", (DL_FUNC) &_testRcppNew_identity_integer, 1},
    {"_testRcppNew_identity_character", (DL_FUNC) &_testRcppNew_identity_character, 1},
    {"_testRcppNew_combine_a", (DL_FUNC) &_testRcppNew_combine_a, 2},
    {"_testRcppNew_combine_b", (DL_FUNC) &_testRcppNew_combine_b, 2},
    {"_testRcppNew_computeSum_a", (DL_FUNC) &_testRcppNew_computeSum_a, 1},
    {"_testRcppNew_computeSum_b", (DL_FUNC) &_testRcppNew_computeSum_b, 1},
    {"_testRcppNew_math_square_a", (DL_FUNC) &_testRcppNew_math_square_a, 1},
    {"_testRcppNew_math_square_b", (DL_FUNC) &_testRcppNew_math_square_b, 1},
    {"_testRcppNew_app_core_version1", (DL_FUNC) &_testRcppNew_app_core_version1, 0},
    {"_testRcppNew_identity_string", (DL_FUNC) &_testRcppNew_identity_string, 1},
    {"_testRcppNew_test_addValues_a", (DL_FUNC) &_testRcppNew_test_addValues_a, 2},
    {"_testRcppNew_test_addValues_b", (DL_FUNC) &_testRcppNew_test_addValues_b, 2},
    {"_testRcppNew_pi_func", (DL_FUNC) &_testRcppNew_pi_func, 0},
    {"_testRcppNew_util_hashCode", (DL_FUNC) &_testRcppNew_util_hashCode, 1},
    {"_testRcppNew_mean1", (DL_FUNC) &_testRcppNew_mean1, 1},
    {"_testRcppNew_mean", (DL_FUNC) &_testRcppNew_mean, 1},
    {"_testRcppNew_gcd_a", (DL_FUNC) &_testRcppNew_gcd_a, 2},
    {"_testRcppNew_gcd_b", (DL_FUNC) &_testRcppNew_gcd_b, 2},
    {"_testRcppNew_process", (DL_FUNC) &_testRcppNew_process, 1},
    {"_testRcppNew_equal_func", (DL_FUNC) &_testRcppNew_equal_func, 2},
    {"_testRcppNew_average_a", (DL_FUNC) &_testRcppNew_average_a, 2},
    {"_testRcppNew_average_b", (DL_FUNC) &_testRcppNew_average_b, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_testRcppNew(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
