# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

minstd_rand <- function(length) {
    .Call(`_testRcppNew_minstd_rand`, length)
}

mt19937 <- function(length) {
    .Call(`_testRcppNew_mt19937`, length)
}

knuth_b <- function(length) {
    .Call(`_testRcppNew_knuth_b`, length)
}

minstd_rand.int <- function(length) {
    .Call(`_testRcppNew_minstd_rand_int`, length)
}

mt19937.int <- function(length) {
    .Call(`_testRcppNew_mt19937_int`, length)
}

knuth_b.int <- function(length) {
    .Call(`_testRcppNew_knuth_b_int`, length)
}

sample <- function( x, size, replace = FALSE ) {
    .Call(`_testRcppNew_sample`, x, size, replace)
}

sample.int <- function( x, size, replace = FALSE ) {
    .Call(`_testRcppNew_sample_int`, x, size, replace)
}

startsWith <- function(str, substr) {
    .Call(`_testRcppNew_startsWith`, str, substr)
}

endsWith <- function(str, substr) {
    .Call(`_testRcppNew_endsWith`, str, substr)
}

replaceSubstring <- function(s, oldSubstr, newSubstr) {
    .Call(`_testRcppNew_replaceSubstring`, s, oldSubstr, newSubstr)
}

toTable.char <- function(x) {
    .Call(`_testRcppNew_toTable_char`, x)
}

power_vector <- function(x, power) {
    .Call(`_testRcppNew_power_vector`, x, power)
}

toTable <- function(x) {
    .Call(`_testRcppNew_toTable`, x)
}

