# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

startsWith <- function(str, substr) {
    .Call(`_testRcppNew_startsWith`, str, substr)
}

endsWith <- function(str, substr) {
    .Call(`_testRcppNew_endsWith`, str, substr)
}

replaceSubstring <- function(s, oldSubstr, newSubstr) {
    .Call(`_testRcppNew_replaceSubstring`, s, oldSubstr, newSubstr)
}

toTable.char <- function(x) {
    .Call(`_testRcppNew_toTable_char`, x)
}

